package goCommsDefinitions

const BottomStackStackName = "BottomStack"
const TopStackName = "TopStack"
const SshStackName = "SshStack"
const MessageNumberStackName = "MsgNum"
const TlsStackName = "TLS"
const WebSocketStackName = "WebSocket"
const PingPongStackName = "PingPong"
const CompressionStackName = "Compress"
const MessageBreakerStackName = "BVIS"
const TransportFactoryCompressedTlsName = "CompressedTlsStack"
const TransportFactoryUnCompressedTlsName = "UncompressedTlsStack"
const TransportFactoryCompressedName = "CompressedStack"
const TransportFactoryUnCompressedName = "UncompressedStack"
const TransportFactoryEmptyName = "EmptyStack"
const WebSocketName = "WebSocketStack"
const ProtoBufferStackName = "ProtoBuf"
const EmptyStackName = "EmptyStack"
const TransportFactoryOnlyTopStack = "OnlyTopStack"
const TransportFactoryOnlyPingPongStack = "OnlyPingPongStack"
const TransportFactoryOnlyMessageCompressorStack = "OnlyMessageCompressorStack"
const TransportFactoryOnlyMessageNumberStack = "OnlyMessageNumberStack"
const TransportFactoryOnlyBvisMessageBreakerStack = "OnlyBvisMessageBreakerStack"
const TransportFactoryOnlyTlsConnectionStack = "OnlyTlsConnectionStack"
const TransportFactoryOnlyBottomStack = "OnlyBottomStack"
const TransportFactoryOnlySSHStack = "OnlySSHBottomStack"
const Socks5 = "Socks5"
const TransportFactorySocks5 = "TransportFactorySocks5"

//sssh
const SshChannelSession = "SshChannelSession"
const TransportFactoryForSshChannelSession = "SshChannelSessionStack"
